help() {
  echo "========================================="
  echo "           COMMANDES DISPONIBLES         "
  echo "========================================="
  echo "  about    : Affiche les informations de l'utilisateur"
  echo "  age      : Affiche l'âge de l'utilisateur"
  echo "  cd       : Change de répertoire courant"
  echo "  help     : Affiche cette liste d'aide"
  echo "  hour     : Affiche l'heure actuelle"
  echo "  mkdir    : Crée un nouveau dossier"
  echo "  open     : Ouvre ou crée un fichier avec Vim"
  echo "  passw    : Modifie le mot de passe utilisateur"
  echo "  profil   : Affiche le profil de l'utilisateur"
  echo "  pwd      : Affiche le chemin du dossier courant"
  echo "  quit     : Quitte l'application"
  echo "  rm       : Supprime un fichier"
  echo "  rmd      : Supprime un dossier"
  echo "  smtp     : Envoie un e-mail via SMTP"
  echo "  touch    : Crée un fichier vide"
  echo "  version  : Affiche la version du programme"
  echo "========================================="
}